package org.swaroopwardhinee.models;

import java.util.Date;

public class ErrorInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_info.id
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_info.error_code
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    private String errorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_info.error_desc
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    private String errorDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_info.created_on
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    private Date createdOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_info.created_by
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_info.modified_on
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    private Date modifiedOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_info.modified_by
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    private String modifiedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_info.id
     *
     * @return the value of error_info.id
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_info.id
     *
     * @param id the value for error_info.id
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_info.error_code
     *
     * @return the value of error_info.error_code
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_info.error_code
     *
     * @param errorCode the value for error_info.error_code
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode == null ? null : errorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_info.error_desc
     *
     * @return the value of error_info.error_desc
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    public String getErrorDesc() {
        return errorDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_info.error_desc
     *
     * @param errorDesc the value for error_info.error_desc
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    public void setErrorDesc(String errorDesc) {
        this.errorDesc = errorDesc == null ? null : errorDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_info.created_on
     *
     * @return the value of error_info.created_on
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_info.created_on
     *
     * @param createdOn the value for error_info.created_on
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_info.created_by
     *
     * @return the value of error_info.created_by
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_info.created_by
     *
     * @param createdBy the value for error_info.created_by
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_info.modified_on
     *
     * @return the value of error_info.modified_on
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    public Date getModifiedOn() {
        return modifiedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_info.modified_on
     *
     * @param modifiedOn the value for error_info.modified_on
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    public void setModifiedOn(Date modifiedOn) {
        this.modifiedOn = modifiedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_info.modified_by
     *
     * @return the value of error_info.modified_by
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_info.modified_by
     *
     * @param modifiedBy the value for error_info.modified_by
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy == null ? null : modifiedBy.trim();
    }
}