package org.swaroopwardhinee.models;

import java.util.Date;

public class RolePermissions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permissions.id
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permissions.role_id
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permissions.permission
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permissions.created_on
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    private Date createdOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permissions.created_by
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permissions.modified_on
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    private Date modifiedOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permissions.modified_by
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    private String modifiedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permissions.id
     *
     * @return the value of role_permissions.id
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permissions.id
     *
     * @param id the value for role_permissions.id
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permissions.role_id
     *
     * @return the value of role_permissions.role_id
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permissions.role_id
     *
     * @param roleId the value for role_permissions.role_id
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permissions.permission
     *
     * @return the value of role_permissions.permission
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permissions.permission
     *
     * @param permission the value for role_permissions.permission
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permissions.created_on
     *
     * @return the value of role_permissions.created_on
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permissions.created_on
     *
     * @param createdOn the value for role_permissions.created_on
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permissions.created_by
     *
     * @return the value of role_permissions.created_by
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permissions.created_by
     *
     * @param createdBy the value for role_permissions.created_by
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permissions.modified_on
     *
     * @return the value of role_permissions.modified_on
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    public Date getModifiedOn() {
        return modifiedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permissions.modified_on
     *
     * @param modifiedOn the value for role_permissions.modified_on
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    public void setModifiedOn(Date modifiedOn) {
        this.modifiedOn = modifiedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permissions.modified_by
     *
     * @return the value of role_permissions.modified_by
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permissions.modified_by
     *
     * @param modifiedBy the value for role_permissions.modified_by
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy == null ? null : modifiedBy.trim();
    }
}