package org.swaroopwardhinee.models;

import java.util.Date;

public class UserRoles {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.id
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.user_id
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.role_id
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.is_default
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    private Boolean isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.is_active
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    private Boolean isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.created_on
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    private Date createdOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.created_by
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.modified_on
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    private Date modifiedOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.modified_by
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    private String modifiedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.id
     *
     * @return the value of user_roles.id
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.id
     *
     * @param id the value for user_roles.id
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.user_id
     *
     * @return the value of user_roles.user_id
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.user_id
     *
     * @param userId the value for user_roles.user_id
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.role_id
     *
     * @return the value of user_roles.role_id
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.role_id
     *
     * @param roleId the value for user_roles.role_id
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.is_default
     *
     * @return the value of user_roles.is_default
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    public Boolean getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.is_default
     *
     * @param isDefault the value for user_roles.is_default
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.is_active
     *
     * @return the value of user_roles.is_active
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.is_active
     *
     * @param isActive the value for user_roles.is_active
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.created_on
     *
     * @return the value of user_roles.created_on
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.created_on
     *
     * @param createdOn the value for user_roles.created_on
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.created_by
     *
     * @return the value of user_roles.created_by
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.created_by
     *
     * @param createdBy the value for user_roles.created_by
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.modified_on
     *
     * @return the value of user_roles.modified_on
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    public Date getModifiedOn() {
        return modifiedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.modified_on
     *
     * @param modifiedOn the value for user_roles.modified_on
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    public void setModifiedOn(Date modifiedOn) {
        this.modifiedOn = modifiedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.modified_by
     *
     * @return the value of user_roles.modified_by
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.modified_by
     *
     * @param modifiedBy the value for user_roles.modified_by
     *
     * @mbggenerated Mon Aug 17 12:19:40 IST 2020
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy == null ? null : modifiedBy.trim();
    }
}