package org.swaroopwardhinee.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.swaroopwardhinee.models.ErrorInfo;
import org.swaroopwardhinee.models.ErrorInfoExample;

public interface ErrorInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_info
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    int countByExample(ErrorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_info
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    int deleteByExample(ErrorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_info
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_info
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    int insert(ErrorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_info
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    int insertSelective(ErrorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_info
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    List<ErrorInfo> selectByExample(ErrorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_info
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    ErrorInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_info
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    int updateByExampleSelective(@Param("record") ErrorInfo record, @Param("example") ErrorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_info
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    int updateByExample(@Param("record") ErrorInfo record, @Param("example") ErrorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_info
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    int updateByPrimaryKeySelective(ErrorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_info
     *
     * @mbggenerated Mon Aug 17 12:20:40 IST 2020
     */
    int updateByPrimaryKey(ErrorInfo record);
}