package org.swaroopwardhinee.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.swaroopwardhinee.models.ForgotPassword;
import org.swaroopwardhinee.models.ForgotPasswordExample;

public interface ForgotPasswordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forgot_password
     *
     * @mbggenerated Tue Aug 18 12:30:27 IST 2020
     */
    int countByExample(ForgotPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forgot_password
     *
     * @mbggenerated Tue Aug 18 12:30:27 IST 2020
     */
    int deleteByExample(ForgotPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forgot_password
     *
     * @mbggenerated Tue Aug 18 12:30:27 IST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forgot_password
     *
     * @mbggenerated Tue Aug 18 12:30:27 IST 2020
     */
    int insert(ForgotPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forgot_password
     *
     * @mbggenerated Tue Aug 18 12:30:27 IST 2020
     */
    int insertSelective(ForgotPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forgot_password
     *
     * @mbggenerated Tue Aug 18 12:30:27 IST 2020
     */
    List<ForgotPassword> selectByExample(ForgotPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forgot_password
     *
     * @mbggenerated Tue Aug 18 12:30:27 IST 2020
     */
    ForgotPassword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forgot_password
     *
     * @mbggenerated Tue Aug 18 12:30:27 IST 2020
     */
    int updateByExampleSelective(@Param("record") ForgotPassword record, @Param("example") ForgotPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forgot_password
     *
     * @mbggenerated Tue Aug 18 12:30:27 IST 2020
     */
    int updateByExample(@Param("record") ForgotPassword record, @Param("example") ForgotPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forgot_password
     *
     * @mbggenerated Tue Aug 18 12:30:27 IST 2020
     */
    int updateByPrimaryKeySelective(ForgotPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forgot_password
     *
     * @mbggenerated Tue Aug 18 12:30:27 IST 2020
     */
    int updateByPrimaryKey(ForgotPassword record);
}