package org.swaroopwardhinee.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.swaroopwardhinee.models.RolePermissions;
import org.swaroopwardhinee.models.RolePermissionsExample;

public interface RolePermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    int countByExample(RolePermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    int deleteByExample(RolePermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    int insert(RolePermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    int insertSelective(RolePermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    List<RolePermissions> selectByExample(RolePermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    RolePermissions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    int updateByExampleSelective(@Param("record") RolePermissions record, @Param("example") RolePermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    int updateByExample(@Param("record") RolePermissions record, @Param("example") RolePermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    int updateByPrimaryKeySelective(RolePermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbggenerated Mon Aug 17 12:20:11 IST 2020
     */
    int updateByPrimaryKey(RolePermissions record);
}